[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "caesar-cipher"
version = "1.0.0"
description = "Caesar Cipher project with CLI and GUI"
authors = [{ name="amer" }]
requires-python = ">=3.10"
